### ISSUE TITLE
NoneType error for model_checkpoint_path

### ISSUE THREAD

**Issue by vineethbabu** [harish2704/FOTS_TF-data#1]
Hi, @harish2704  i am trying to run detection on custom data, however I am getting the following error.
**AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'**

could you pls tell me why this is? Is it because the checkpoint file is not availabe?

**Comment by harish2704** [comment]
Unfortunately, The file with filename `checkpoint` is not included in the uploaded zip file ( which is required for the tensorflow )
So, just create a file "checkpoint" in the same directory , with content 
```
model_checkpoint_path: "./model.ckpt-44441"
```

which will probably solve the problem

**Comment by AmrMaghraby** [comment]
The file uploaded dont want to unzip are you sure it is working fine!!!

**Comment by harish2704** [comment]
Yes. I was able to run the model

**Comment by AmrMaghraby** [comment]
Did you train it successfully?

**Comment by harish2704** [comment]
I was able to evaluate it successfully. Didn't tried to train it.

My primary objective was to check the performance of "text detection" branch of FOTS network

**Comment by AmrMaghraby** [comment]
Could you share it again on Google Drive? The one which it is shared here not working (could not unzip it)?

**Comment by harish2704** [comment]
I checked the zip and found it is a valid zip file. Please see the screen shot of my terminal session 

![image](https://user-images.githubusercontent.com/1652903/59548671-4b109d80-8f70-11e9-8945-a1a3a7009c0a.png)
